# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UdpTest_iOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UdpTest_iOS
pod 'CocoaAsyncSocket', '~> 7.5.1'
pod 'Masonry', '~> 1.0.2'
end
